language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ebbemelosorensen/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true ebbemelosorensen/frontend npm run test

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-907718596887"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
